---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids:
    - sg-97e55ef2
  instance_type: c3.xlarge
  interface: private
  subnet_id: subnet-a792da8f
  tags:
    Env: private
    Type: test
  iam_profile_name: test-ec2dnsserver

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environment: dev
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret

platforms:
  - name: ubuntu-14.04

suites:
  - name: server
    run_list:
      - recipe[et_monitor_server::default]
    attributes:
      shinken:
        services: {}
        hostgroups: {}
