---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: dev
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret

platforms:
  - name: ubuntu-12.04

suites:
  - name: server
    driver_config:
      network:
      - [ 'private_network', {ip: '192.168.33.11'}]
    run_list:
      - recipe[et_hostname::default]
      - recipe[et_monitor_server::default]
    attributes:
      shinken:
        services: {}
        hostgroups: {}
